/**
 * The conformal thresholds against MAPIE (Learn Then Test, fixed-sequence) and crepes (class-conditional
 * conformal p-values). The fixture is generated by scripts/make_conformal_golden.py.
 */
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

import { binomialCdf, conformalLowerThreshold, conformalUpperThreshold } from '../src/index.ts';

interface Side { params: number[]; p_values: number[]; threshold: number | null; threshold_builtin?: number | null }
interface Case {
  name: string; alpha: number; beta: number; delta: number; epsilon: number;
  positives: number[]; negatives: number[];
  recall: Side & { misses: number[] };
  false_alarm: Side & { alarms: number[] };
  crepes: { grid: number[]; p_positive: number[]; p_negative: number[] };
}
const golden = JSON.parse(readFileSync(new URL('./fixtures/conformal-golden.json', import.meta.url), 'utf8')) as { versions: Record<string, string>; cases: Case[] };

for (const c of golden.cases) {
  test(`MAPIE ${golden.versions.mapie}: ${c.name}`, () => {
    const recall = conformalLowerThreshold(c.positives, c.alpha, c.delta);
    assert.equal(recall, c.recall.threshold, 'PAC recall threshold (MAPIE, miss-rate risk)');
    // MAPIE's built-in "recall" risk can land a rank lower (see the generator): never above ours.
    if (c.recall.threshold_builtin !== null) assert.ok(recall !== null && c.recall.threshold_builtin! <= recall, 'built-in recall risk');
    assert.equal(conformalUpperThreshold(c.negatives, c.beta, c.delta), c.false_alarm.threshold, 'PAC false-alarm threshold');
    // MAPIE's binary p-value is min(Hoeffding, P(Bin(n, α) <= ⌈n·r̂⌉)) with r̂ = count / n. The
    // Hoeffding term is a Chernoff bound on the same tail, so this is the exact binomial ours
    // uses - reproduced with MAPIE's float arithmetic, and checked never to be less conservative.
    const check = (side: Side, counts: number[], n: number, rate: number, rHat: (k: number) => number) => counts.forEach((k, i) => {
      const r = rHat(k);
      const rc = Math.min(r, rate);
      const h1 = (rc === 0 ? 0 : rc * Math.log(rc / rate)) + (1 - rc) * Math.log((1 - rc) / (1 - rate));
      const mapie = Math.min(Math.exp(-n * h1), binomialCdf(Math.ceil(n * r), n, rate));
      assert.ok(Math.abs(mapie - side.p_values[i]) <= 1e-8, `p-value at ${side.params[i]}: ${mapie} vs MAPIE ${side.p_values[i]}`);
      assert.ok(side.p_values[i] >= binomialCdf(k, n, rate) - 1e-12, `MAPIE is less conservative than the exact test at ${side.params[i]}`);
    });
    const [nPos, nNeg] = [c.positives.length, c.negatives.length];
    check(c.recall, c.recall.misses, nPos, c.alpha, (k) => k / nPos);
    check(c.false_alarm, c.false_alarm.alarms, nNeg, c.beta, (k) => k / nNeg);
  });

  test(`crepes ${golden.versions.crepes}: ${c.name}`, () => {
    // At or above the expected-guarantee threshold exactly when the positive label's p-value exceeds ε...
    const floor = conformalLowerThreshold(c.positives, c.epsilon) ?? -Infinity;
    c.crepes.grid.forEach((s, i) => assert.equal(s >= floor, c.crepes.p_positive[i] > c.epsilon, `score ${s}: p+ ${c.crepes.p_positive[i]}`));
    // ...and fires exactly when the negative label's p-value is at most ε.
    const fa = conformalUpperThreshold(c.negatives, c.epsilon) ?? Infinity;
    c.crepes.grid.forEach((s, i) => assert.equal(s >= fa, c.crepes.p_negative[i] <= c.epsilon, `score ${s}: p- ${c.crepes.p_negative[i]}`));
  });
}
